name: test

on:
  push:
    branches: "**"
    pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Unit test
        run: ./gradlew test

      - name: Set up emulator
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 30
            emulator-version: '30.8.4'
            profile: ${{ runner.OS }}-google_apis_playstore

      - name: Start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          emulator-version: '30.8.4'
          profile: ${{ runner.OS }}-google_apis_playstore
          action: start

      - name: Wait for emulator to start
        uses: reactivecircus/android-wait-for-emulator@v2
        with:
          timeout: 300000


      - name: Instrumented test
        run: ./gradlew connectedAndroidTest



