name: test

on:
  push:
    branches: "**"
    pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Unit test
        run: ./gradlew test

      - name: Instrumented test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest



